services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "80:80"
        depends_on:
            - app
            - scheduler
        container_name: app_nginx
        networks:
            - base

    app:
        build:
            args:
                user: www
                uid: 1000
            context: ./
            dockerfile: docker/app/Dockerfile
        image: base
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - db
            - redis
            - graylog
        networks:
            - base
        command: ["/usr/local/bin/entrypoint.sh"]

    db:
        image: postgres:14
        restart: always
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '5433:5432'
        container_name: db
        networks:
            - base

    scheduler:
        build:
            context: .
            dockerfile: docker/scheduler/Dockerfile
        image: scheduler
        volumes:
            - ./:/var/www
        depends_on:
            - app
        container_name: scheduler
        networks:
            - base

    redis:
        container_name: redis
        image: redis:alpine
        restart: always
        ports:
            - '${REDIS_PORT}:6379'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
        volumes:
            - redis:/data
        networks:
            - base

networks:
    base:
        driver: bridge

volumes:
    db:
        driver: local
    redis:
        driver: local
